/*
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.metaform.client;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets MetaformTableColumnType
 */
public enum MetaformTableColumnType {
  
  HIDDEN("hidden"),
  
  TEXT("text"),
  
  AUTOCOMPLETE("autocomplete"),
  
  NUMBER("number"),
  
  ENUM("enum"),
  
  DATE("date"),
  
  TIME("time"),
  
  HTML("html"),
  
  BUTTON("button");

  private String value;

  MetaformTableColumnType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MetaformTableColumnType fromValue(String text) {
    for (MetaformTableColumnType b : MetaformTableColumnType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

