/*
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.metaform.client;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.metaform.client.MetaformScript;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MetaformScripts
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-29T14:02:51.404+03:00")
public class MetaformScripts {
  @JsonProperty("afterSubmit")
  private MetaformScript afterSubmit = null;

  public MetaformScripts afterSubmit(MetaformScript afterSubmit) {
    this.afterSubmit = afterSubmit;
    return this;
  }

   /**
   * Get afterSubmit
   * @return afterSubmit
  **/
  @ApiModelProperty(value = "")
  public MetaformScript getAfterSubmit() {
    return afterSubmit;
  }

  public void setAfterSubmit(MetaformScript afterSubmit) {
    this.afterSubmit = afterSubmit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetaformScripts metaformScripts = (MetaformScripts) o;
    return Objects.equals(this.afterSubmit, metaformScripts.afterSubmit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(afterSubmit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetaformScripts {\n");
    
    sb.append("    afterSubmit: ").append(toIndentedString(afterSubmit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

