/*
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.metaform.client;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MetaformFieldPermissioncontexts
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-29T14:02:51.404+03:00")
public class MetaformFieldPermissioncontexts {
  @JsonProperty("view-group")
  private Boolean viewGroup = false;

  @JsonProperty("edit-group")
  private Boolean editGroup = false;

  @JsonProperty("notify-group")
  private Boolean notifyGroup = false;

  public MetaformFieldPermissioncontexts viewGroup(Boolean viewGroup) {
    this.viewGroup = viewGroup;
    return this;
  }

   /**
   * Field value is used as security group with view permission
   * @return viewGroup
  **/
  @ApiModelProperty(value = "Field value is used as security group with view permission")
  public Boolean isViewGroup() {
    return viewGroup;
  }

  public void setViewGroup(Boolean viewGroup) {
    this.viewGroup = viewGroup;
  }

  public MetaformFieldPermissioncontexts editGroup(Boolean editGroup) {
    this.editGroup = editGroup;
    return this;
  }

   /**
   * Field value is used as security group with edit permission
   * @return editGroup
  **/
  @ApiModelProperty(value = "Field value is used as security group with edit permission")
  public Boolean isEditGroup() {
    return editGroup;
  }

  public void setEditGroup(Boolean editGroup) {
    this.editGroup = editGroup;
  }

  public MetaformFieldPermissioncontexts notifyGroup(Boolean notifyGroup) {
    this.notifyGroup = notifyGroup;
    return this;
  }

   /**
   * Field value is used as security group with notification permission
   * @return notifyGroup
  **/
  @ApiModelProperty(value = "Field value is used as security group with notification permission")
  public Boolean isNotifyGroup() {
    return notifyGroup;
  }

  public void setNotifyGroup(Boolean notifyGroup) {
    this.notifyGroup = notifyGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetaformFieldPermissioncontexts metaformFieldPermissioncontexts = (MetaformFieldPermissioncontexts) o;
    return Objects.equals(this.viewGroup, metaformFieldPermissioncontexts.viewGroup) &&
        Objects.equals(this.editGroup, metaformFieldPermissioncontexts.editGroup) &&
        Objects.equals(this.notifyGroup, metaformFieldPermissioncontexts.notifyGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(viewGroup, editGroup, notifyGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetaformFieldPermissioncontexts {\n");
    
    sb.append("    viewGroup: ").append(toIndentedString(viewGroup)).append("\n");
    sb.append("    editGroup: ").append(toIndentedString(editGroup)).append("\n");
    sb.append("    notifyGroup: ").append(toIndentedString(notifyGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

