/*
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.metaform.client;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.metaform.client.MetaformScript;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MetaformScripts
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-29T18:07:31.883+03:00")
public class MetaformScripts {
  @JsonProperty("afterCreateReply")
  private List<MetaformScript> afterCreateReply = null;

  @JsonProperty("afterUpdateReply")
  private List<MetaformScript> afterUpdateReply = null;

  public MetaformScripts afterCreateReply(List<MetaformScript> afterCreateReply) {
    this.afterCreateReply = afterCreateReply;
    return this;
  }

  public MetaformScripts addAfterCreateReplyItem(MetaformScript afterCreateReplyItem) {
    if (this.afterCreateReply == null) {
      this.afterCreateReply = new ArrayList<MetaformScript>();
    }
    this.afterCreateReply.add(afterCreateReplyItem);
    return this;
  }

   /**
   * List of scripts run after new reply is created
   * @return afterCreateReply
  **/
  @ApiModelProperty(value = "List of scripts run after new reply is created")
  public List<MetaformScript> getAfterCreateReply() {
    return afterCreateReply;
  }

  public void setAfterCreateReply(List<MetaformScript> afterCreateReply) {
    this.afterCreateReply = afterCreateReply;
  }

  public MetaformScripts afterUpdateReply(List<MetaformScript> afterUpdateReply) {
    this.afterUpdateReply = afterUpdateReply;
    return this;
  }

  public MetaformScripts addAfterUpdateReplyItem(MetaformScript afterUpdateReplyItem) {
    if (this.afterUpdateReply == null) {
      this.afterUpdateReply = new ArrayList<MetaformScript>();
    }
    this.afterUpdateReply.add(afterUpdateReplyItem);
    return this;
  }

   /**
   * List of scripts run after a reply is updated
   * @return afterUpdateReply
  **/
  @ApiModelProperty(value = "List of scripts run after a reply is updated")
  public List<MetaformScript> getAfterUpdateReply() {
    return afterUpdateReply;
  }

  public void setAfterUpdateReply(List<MetaformScript> afterUpdateReply) {
    this.afterUpdateReply = afterUpdateReply;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetaformScripts metaformScripts = (MetaformScripts) o;
    return Objects.equals(this.afterCreateReply, metaformScripts.afterCreateReply) &&
        Objects.equals(this.afterUpdateReply, metaformScripts.afterUpdateReply);
  }

  @Override
  public int hashCode() {
    return Objects.hash(afterCreateReply, afterUpdateReply);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetaformScripts {\n");
    
    sb.append("    afterCreateReply: ").append(toIndentedString(afterCreateReply)).append("\n");
    sb.append("    afterUpdateReply: ").append(toIndentedString(afterUpdateReply)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

