swagger: '2.0'
info:
  title: Metaform REST API
  description: REST API for Metaform
  version: 0.0.1
schemes:
  - https
basePath: /
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - bearer: []
paths:
  '/organizations/{organizationId}/metaforms':
    get:
      operationId: listMetaforms
      summary: Lists Metaforms 
      description: Lists Metaforms from the organization. Logged user must have proper 
        permissions to organization, otherwise forbidden is returned instead.
      tags:
        - Metaforms
      parameters:
        - name: organizationId
          required: true
          in: path
          description: Organization id
          type: string
          format: uuid
      responses:
        '200':
          description: A metaform
          schema:
            $ref: '#/definitions/Metaform'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/organizations/{organizationId}/metaforms/{metaformId}':
    get:
      operationId: findMetaform
      summary: Finds single Metaform 
      description: Finds a single Metaform
      tags:
        - Metaforms
      parameters:
        - name: organizationId
          required: true
          in: path
          description: Organization id
          type: string
          format: uuid
        - name: metaformId
          required: true
          in: path
          description: Metaform id
          type: string
          format: uuid
      responses:
        '200':
          description: A metaform
          schema:
            $ref: '#/definitions/Metaform'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/organizations/{organizationId}/metaforms/{metaformId}/replies':
    get:
      operationId: listReplies
      summary: Lists form replies 
      description: Lists form replies
      tags:
        - Replies
      parameters:
        - name: organizationId
          required: true
          in: path
          description: Organization id
          type: string
          format: uuid
        - name: metaformId
          required: true
          in: path
          description: Metaform id
          type: string
          format: uuid
        - name: userId
          in: query
          description: 
            Filter results by user id. Defaults to logged user. If this parameter is 
            not specified all replies are returned, this requires logged user to have
            proper permission to do so
          type: integer
          format: uuid
      responses:
        '200':
          description: A reply
          schema:
            $ref: '#/definitions/Reply'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/organizations/{organizationId}/metaforms/{metaformId}/replies/{replyId}':
    get:
      operationId: findReply
      summary: Find a single reply
      description: Finds single reply by id
      tags:
        - Replies
      parameters:
        - name: organizationId
          required: true
          in: path
          description: Organization id
          type: string
          format: uuid
        - name: metaformId
          required: true
          in: path
          description: Metaform id
          type: string
          format: uuid
        - name: replyId
          required: true
          in: path
          description: Reply id
          type: string
          format: uuid
      responses:
        '200':
          description: A reply
          schema:
            $ref: '#/definitions/Reply'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
    put:
      operationId: updateReply
      summary: Updates reply
      description: Updates reply
      tags:
        - Replies
      parameters:
        - name: organizationId
          required: true
          in: path
          description: Organization id
          type: string
          format: uuid
        - name: metaformId
          required: true
          in: path
          description: Metaform id
          type: string
          format: uuid
        - name: replyId
          required: true
          in: path
          description: Reply id
          type: string
          format: uuid
        - name: payload
          in: body
          description: Payload
          required: true
          schema:
            $ref: '#/definitions/Reply'
      responses:
        '201':
          description: Empty response indicating a succesfull update
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
definitions:
  Reply:
    required:
      - values
    type: object
    properties:
      userId:
        type: string
        format: uuid
      values:
        type: object
        
  Metaform:
    type: object
    properties:
      title: 
        type: "string"
      sections: 
        type: "array"
        items: 
          $ref: '#/definitions/MetaformSection'
          
  MetaformSection:
    type: "object"
    properties: 
      visible-if:
        $ref: '#/definitions/MetaformVisibleIf'
      fields: 
        type: "array"
        items: 
          $ref: '#/definitions/MetaformField'
          
  MetaformField:
    type: "object"
    required:
      - type
      - name
    properties: 
      visible-if:
        $ref: '#/definitions/MetaformVisibleIf'
      name: 
        type: "string"
        description: Field name
      type: 
        type: "string"
        enum:
          - text
          - hidden
          - email
          - number
          - memo
          - boolean
          - radio
          - checklist
          - date
          - time
          - date-time
          - files
          - table
          - logo
          - small-text
          - html
          - submit
          - select
          - autocomplete
          - autocomplete-multiple        
      title: 
        type: "string"
      required: 
        type: "boolean"
      contexts: 
        type: "string"
      placeholder: 
        type: "string"
      class:
        type: "string"
      readonly:
        type: "boolean"
      help:
        type: "string"
      default:
        description: a default value for a field
        type: "string"
      min:
        type: "integer"
        format: int32
        description: Minimum value for a field. Only for number fields
      max:
        type: "integer"
        format: int32
        description: Maximum value for a field. Only for number fields
      step:
        type: "integer"
        format: int32
        description: Value step for a field. Only for number fields
      checked:
        type: "boolean"
        description: Whether checkbox should be checked by default. Only for checkbox fields
      printable:
        type: "boolean"
        description: Defines whether field is printable or not. Only for table fields        
      options:
        type: "array"
        description: Options for radio, checklist, select fields
        items: 
          $ref: '#/definitions/MetaformFieldOption'
      source-url:
        type: "string"
        description: Source url for autocomplete and autocomplete-multiple fields
        format: "url"
      upload-url:
        type: "string"
        description: Upload url for files field.
        format: "url"
      single-file:
        type: "boolean"
        description: Defines whether file fields allow multiple files or just one
      only-images:
        type: "boolean"
        description: Defines whether file fields allow only images
      max-file-size:
        type: "integer"
        format: int64
        description: Maximum upload size for image filds
      draggable:
        type: "boolean"
        description: Defines whether table rows should be draggable.
      columns:
        type: "array"
        description: Columns for table fields
        items:
          $ref: '#/definitions/MetaformTableColumn'
      src: 
        type: "string"
        description: Url for logo field.
        format: "url"
      text:
        type: "string"
        description: Text for small field.
      html:
        type: "string"
        description: Html code for html field.

  MetaformTableColumn:
    type: "object"
    properties:
      type:
        type: "string"
        enum:
          - hidden
          - text
          - autocomplete
          - number
          - enum
          - date
          - time
          - html
          - button
      title:
        type: "string"
        description: Column title
      calculate-sum:
        type: "boolean"
        description: Defines column should automatically calculate sum
      sum-postfix:
        type: "string"
        description: Postfix for calculated sum
      column-width:
        type: "integer"
        description: Defines column width
        format: int32
      placeholder:
        type: "string"
        description: Placeholder for column field
      readonly:
        type: "boolean"
        description: Defines column as readonly
      required:
        type: "boolean"
        description: Defines column as requires
      source-url:
        type: "string"
        format: "url"
        description: Defines source url for autocomplete columns
      html:
        type: "string"
        description: Html code for html columns
      action:
        type: "string"
        description: Action for button columns
      values:
        type: "object"
        description: Values for enum columns
        properties:
          value: 
            type: "string"
          other:
            type: "string"
          text:
            type: "string"
        
  MetaformFieldOption:
    type: "object"
    description: Option object for Metaform field
    required:
      - name
      - text
    properties:
      name:
        description: Option name
        type: "string"
      text:
        description: Option text
        type: "string"
      checked:
        description: Defines whether option should be checked by default.
        type: boolean
        
  MetaformVisibleIf:
    type: "object"
    description: Rule that defines whether specified object is visible
    properties:
      field: 
        type: "string"
        description: Field where the visible if rule is relative to
      equals:
        type: "string"
        description: Value must be equal to this value
      not-equals:
        type: "string"
        description: Value must be not equal to this value
      and:
        type: "array"
        items: 
          $ref: '#/definitions/MetaformVisibleIf'
      or:
        type: "array"
        items: 
          $ref: '#/definitions/MetaformVisibleIf'
          
  InternalServerError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Forbidden:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  BadRequest:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotImplemented:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotFound:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
