/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MetaformApiClient) {
      root.MetaformApiClient = {};
    }
    root.MetaformApiClient.MetaformTableColumnType = factory(root.MetaformApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class MetaformTableColumnType.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "hidden"
     * @const
     */
    "hidden": "hidden",
    /**
     * value: "text"
     * @const
     */
    "text": "text",
    /**
     * value: "autocomplete"
     * @const
     */
    "autocomplete": "autocomplete",
    /**
     * value: "number"
     * @const
     */
    "number": "number",
    /**
     * value: "enum"
     * @const
     */
    "enum": "enum",
    /**
     * value: "date"
     * @const
     */
    "date": "date",
    /**
     * value: "time"
     * @const
     */
    "time": "time",
    /**
     * value: "html"
     * @const
     */
    "html": "html",
    /**
     * value: "button"
     * @const
     */
    "button": "button"  };

  /**
   * Returns a <code>MetaformTableColumnType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/MetaformTableColumnType} The enum <code>MetaformTableColumnType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


