/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MetaformFieldType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MetaformFieldType'));
  } else {
    // Browser globals (root is window)
    if (!root.MetaformApiClient) {
      root.MetaformApiClient = {};
    }
    root.MetaformApiClient.Metafield = factory(root.MetaformApiClient.ApiClient, root.MetaformApiClient.MetaformFieldType);
  }
}(this, function(ApiClient, MetaformFieldType) {
  'use strict';




  /**
   * The Metafield model module.
   * @module model/Metafield
   * @version 0.0.7
   */

  /**
   * Constructs a new <code>Metafield</code>.
   * @alias module:model/Metafield
   * @class
   * @param name {String} Field name
   * @param type {module:model/MetaformFieldType} 
   */
  var exports = function(name, type) {
    var _this = this;


    _this['name'] = name;
    _this['type'] = type;


  };

  /**
   * Constructs a <code>Metafield</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Metafield} obj Optional instance to populate.
   * @return {module:model/Metafield} The populated <code>Metafield</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = MetaformFieldType.constructFromObject(data['type']);
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'Boolean');
      }
      if (data.hasOwnProperty('contexts')) {
        obj['contexts'] = ApiClient.convertToType(data['contexts'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Field name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/MetaformFieldType} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Boolean} time
   */
  exports.prototype['time'] = undefined;
  /**
   * @member {Array.<String>} contexts
   */
  exports.prototype['contexts'] = undefined;



  return exports;
}));


