/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MetaformApiClient) {
      root.MetaformApiClient = {};
    }
    root.MetaformApiClient.ReplyExportFormat = factory(root.MetaformApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class ReplyExportFormat.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "XLSX"
     * @const
     */
    "XLSX": "XLSX",
    /**
     * value: "PDF"
     * @const
     */
    "PDF": "PDF"  };

  /**
   * Returns a <code>ReplyExportFormat</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ReplyExportFormat} The enum <code>ReplyExportFormat</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


