/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetaformApiClient);
  }
}(this, function(expect, MetaformApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetaformApiClient.MetaformTableColumn();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetaformTableColumn', function() {
    it('should create an instance of MetaformTableColumn', function() {
      // uncomment below and update the code to test MetaformTableColumn
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be.a(MetaformApiClient.MetaformTableColumn);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property calculateSum (base name: "calculate-sum")', function() {
      // uncomment below and update the code to test the property calculateSum
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property sumPostfix (base name: "sum-postfix")', function() {
      // uncomment below and update the code to test the property sumPostfix
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property columnWidth (base name: "column-width")', function() {
      // uncomment below and update the code to test the property columnWidth
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property placeholder (base name: "placeholder")', function() {
      // uncomment below and update the code to test the property placeholder
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property readonly (base name: "readonly")', function() {
      // uncomment below and update the code to test the property readonly
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property required (base name: "required")', function() {
      // uncomment below and update the code to test the property required
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property sourceUrl (base name: "source-url")', function() {
      // uncomment below and update the code to test the property sourceUrl
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property html (base name: "html")', function() {
      // uncomment below and update the code to test the property html
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

    it('should have the property values (base name: "values")', function() {
      // uncomment below and update the code to test the property values
      //var instane = new MetaformApiClient.MetaformTableColumn();
      //expect(instance).to.be();
    });

  });

}));
