/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetaformApiClient);
  }
}(this, function(expect, MetaformApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetaformApiClient.MetaformFieldPermissioncontexts();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetaformFieldPermissioncontexts', function() {
    it('should create an instance of MetaformFieldPermissioncontexts', function() {
      // uncomment below and update the code to test MetaformFieldPermissioncontexts
      //var instane = new MetaformApiClient.MetaformFieldPermissioncontexts();
      //expect(instance).to.be.a(MetaformApiClient.MetaformFieldPermissioncontexts);
    });

    it('should have the property viewGroup (base name: "view-group")', function() {
      // uncomment below and update the code to test the property viewGroup
      //var instane = new MetaformApiClient.MetaformFieldPermissioncontexts();
      //expect(instance).to.be();
    });

    it('should have the property editGroup (base name: "edit-group")', function() {
      // uncomment below and update the code to test the property editGroup
      //var instane = new MetaformApiClient.MetaformFieldPermissioncontexts();
      //expect(instance).to.be();
    });

    it('should have the property notifyGroup (base name: "notify-group")', function() {
      // uncomment below and update the code to test the property notifyGroup
      //var instane = new MetaformApiClient.MetaformFieldPermissioncontexts();
      //expect(instance).to.be();
    });

  });

}));
