/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Attachment { 
    /**
     * Entity identifier
     */
    id?: string;
    /**
     * Attachment's name
     */
    name?: string;
    /**
     * Attachment's content type (e.g. application/pdf)
     */
    contentType?: string;
}
export interface AttachmentOpt { 
    /**
     * Entity identifier
     */
    id?: string;
    /**
     * Attachment's name
     */
    name?: string;
    /**
     * Attachment's content type (e.g. application/pdf)
     */
    contentType?: string;
}
