/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Email notification
 */
export interface EmailNotification { 
    id?: string;
    subjectTemplate: string;
    contentTemplate: string;
    emails: Array<string>;
}
export interface EmailNotificationOpt { 
    id?: string;
    subjectTemplate?: string;
    contentTemplate?: string;
    emails?: Array<string>;
}
