/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ExportThemeFile { 
    id?: string;
    path: string;
    themeId: string;
    content: string;
}
export interface ExportThemeFileOpt { 
    id?: string;
    path?: string;
    themeId?: string;
    content?: string;
}
