/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetaformScript } from './metaformScript';


export interface MetaformScripts { 
    /**
     * List of scripts run after new reply is created
     */
    afterCreateReply?: Array<MetaformScript>;
    /**
     * List of scripts run after a reply is updated
     */
    afterUpdateReply?: Array<MetaformScript>;
}
export interface MetaformScriptsOpt { 
    /**
     * List of scripts run after new reply is created
     */
    afterCreateReply?: Array<MetaformScript>;
    /**
     * List of scripts run after a reply is updated
     */
    afterUpdateReply?: Array<MetaformScript>;
}
