/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Values for enum columns
 */
export interface MetaformTableColumnValues { 
    value?: string;
    other?: string;
    text?: string;
}
export interface MetaformTableColumnValuesOpt { 
    value?: string;
    other?: string;
    text?: string;
}
