/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Rule that defines whether specified object is visible
 */
export interface MetaformVisibleIf { 
    /**
     * Field where the visible if rule is relative to
     */
    field?: string;
    /**
     * Value must be equal to this value. If value is specified \"true\" field must have any value selected
     */
    equals?: string;
    /**
     * Value must be not equal to this value.
     */
    notEquals?: string;
    and?: Array<MetaformVisibleIf>;
    or?: Array<MetaformVisibleIf>;
}
export interface MetaformVisibleIfOpt { 
    /**
     * Field where the visible if rule is relative to
     */
    field?: string;
    /**
     * Value must be equal to this value. If value is specified \"true\" field must have any value selected
     */
    equals?: string;
    /**
     * Value must be not equal to this value.
     */
    notEquals?: string;
    and?: Array<MetaformVisibleIf>;
    or?: Array<MetaformVisibleIf>;
}
