/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type MetaformFieldType = 'text' | 'url' | 'hidden' | 'email' | 'number' | 'memo' | 'boolean' | 'radio' | 'checklist' | 'date' | 'time' | 'date-time' | 'files' | 'table' | 'logo' | 'small-text' | 'html' | 'submit' | 'select' | 'autocomplete' | 'autocomplete-multiple';

export const MetaformFieldType = {
    Text: 'text' as MetaformFieldType,
    Url: 'url' as MetaformFieldType,
    Hidden: 'hidden' as MetaformFieldType,
    Email: 'email' as MetaformFieldType,
    Number: 'number' as MetaformFieldType,
    Memo: 'memo' as MetaformFieldType,
    Boolean: 'boolean' as MetaformFieldType,
    Radio: 'radio' as MetaformFieldType,
    Checklist: 'checklist' as MetaformFieldType,
    Date: 'date' as MetaformFieldType,
    Time: 'time' as MetaformFieldType,
    DateTime: 'date-time' as MetaformFieldType,
    Files: 'files' as MetaformFieldType,
    Table: 'table' as MetaformFieldType,
    Logo: 'logo' as MetaformFieldType,
    SmallText: 'small-text' as MetaformFieldType,
    Html: 'html' as MetaformFieldType,
    Submit: 'submit' as MetaformFieldType,
    Select: 'select' as MetaformFieldType,
    Autocomplete: 'autocomplete' as MetaformFieldType,
    AutocompleteMultiple: 'autocomplete-multiple' as MetaformFieldType
};
