/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetaformScripts } from './metaformScripts';
import { MetaformSection } from './metaformSection';


export interface Metaform { 
    id?: string;
    replyStrategy?: Metaform.ReplyStrategyEnum;
    exportThemeId?: string;
    /**
     * Are anonymous replies allowed or not
     */
    allowAnonymous?: boolean;
    /**
     * Are drafts allowed or not
     */
    allowDrafts?: boolean;
    title?: string;
    sections?: Array<MetaformSection>;
    scripts?: MetaformScripts;
}
export interface MetaformOpt { 
    id?: string;
    replyStrategy?: Metaform.ReplyStrategyEnum;
    exportThemeId?: string;
    /**
     * Are anonymous replies allowed or not
     */
    allowAnonymous?: boolean;
    /**
     * Are drafts allowed or not
     */
    allowDrafts?: boolean;
    title?: string;
    sections?: Array<MetaformSection>;
    scripts?: MetaformScripts;
}
export namespace Metaform {
    export type ReplyStrategyEnum = 'PUBLIC' | 'PRIVATE';
    export const ReplyStrategyEnum = {
        PUBLIC: 'PUBLIC' as ReplyStrategyEnum,
        PRIVATE: 'PRIVATE' as ReplyStrategyEnum
    };
}
