/**
 * Metaform REST API
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type MetaformTableColumnType = 'hidden' | 'text' | 'url' | 'email' | 'autocomplete' | 'number' | 'enum' | 'date' | 'time' | 'html' | 'button';

export const MetaformTableColumnType = {
    Hidden: 'hidden' as MetaformTableColumnType,
    Text: 'text' as MetaformTableColumnType,
    Url: 'url' as MetaformTableColumnType,
    Email: 'email' as MetaformTableColumnType,
    Autocomplete: 'autocomplete' as MetaformTableColumnType,
    Number: 'number' as MetaformTableColumnType,
    Enum: 'enum' as MetaformTableColumnType,
    Date: 'date' as MetaformTableColumnType,
    Time: 'time' as MetaformTableColumnType,
    Html: 'html' as MetaformTableColumnType,
    Button: 'button' as MetaformTableColumnType
};
